name: Flujo de trabajo Reusable ejemplo
on:
  workflow_call:
    inputs:
      SERVER_NAME:
        description: 'Nombre del Servidor de Integracion, donde se realizara el despliegue'
        required: true
        type: string
jobs:
  print-username:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.SERVER_NAME }}
