name: Llamar Flujo de Trabajo

on:
  pull_request:
    branches: 
      - develop
      
  workflow_dispatch:
  
jobs: 
  call-workflow-passing-data:
    uses: ./.github/workflows/prueba_wf_reutilizable.yml
    with:
      SERVER_NAME: server
