name: Flujo de trabajo Reusable ejemplo
on:
  workflow_call:
    inputs:
      SERVER_NAME:
        description: 'Nombre del Servidor de Integracion, donde se realizara el despliegue'
        required: true
        type: string
jobs:
  print-SERVER_NAME:
    runs-on: [self-hosted, linux, x64, BUS]
    timeout-minutes: 5
    steps:
      - name: Print the input name to STDOUT
        run: echo The SERVER_NAME is ${{ inputs.SERVER_NAME }}
